### ISSUE TITLE
upload file from stdin not working with sftp

### ISSUE THREAD

**Issue by bitcloud** [lavv17/lftp#104] opened 2014-12-01 03:54 UTC
I try to upload a file to my backup server via sftp. Because I pipe it through gpg I use the 'put /dev/stdin -o filename' approach but this seems to be broken with sftp or am I missing something?

```
#> echo test | /usr/bin/lftp sftp://user:pass@backupserver.de -c 'put /dev/stdin -o lftp_test_stream.txt;'
'/dev/stdin' at 0 (0%) [Sending data]
```

the command stalls at that point and nothing else happens until some time later.

```
put: /dev/stdin: cannot seek on data source
```

LFTP is Version 4.6.0 Libraries used: Readline 6.2, GnuTLS 3.3.8, zlib 1.2.7

**Comment by Witiko** [comment] 2017-09-23 21:21
I am getting the same error with the 4.7.4 and 4.8.1 `lftp` binaries distributed by the Debian project. Can you confirm that there hasn't been a regression since the issue has been closed?

**Comment by Witiko** [comment] 2017-09-24 09:48
I appologize about a false alarm, I misspecified the port, which lead to the error message:
```
$ yes | lftp -p $wrong_port sftp://$user:$pass@$host -e 'put /dev/stdin -o buffer'
put: /dev/stdin: cannot seek on data source
```
It should be safe to close the issue, although the error message is arguably misleading.

**Closed** 2017-09-25 10:05 UTC
