### ISSUE TITLE
connecting to the wrong port with max-retries crashes lftp

### ISSUE THREAD

**Issue by gpetrov** [lavv17/lftp#390] opened 2017-09-15 21:43 UTC
when trying to connect to invalid ftp port, after the maxretries are consumed an exception occurs:

Fatal error: max-retries exceeded
assertion "ptr(x.heap_index)==&x" failed: file "xheap.h", line 127, function: void xheap<T>::remove(xheap<T>::node&) [with T = Timer]
1 [main] lftp 20404 cygwin_exception::open_stackdumpfile: Dumping stack trace to lftp.exe.stackdump]

compiled with cygwin on Windows 10

**Comment by lavv17** [comment] 2017-09-22 12:12
I cannot reproduce it. Can you show me the complete debug from lftp?

**Comment by gpetrov** [comment] 2017-09-22 12:58
Turned to be some problem with the compiled cygwin version.
When compiled with MSYS2 everything was fine at lest for version 4.7.8

When trying ver 4.8.1 - there were some compilation errors, maybe you can help, see
https://github.com/Alexpux/MSYS2-packages/issues/1006

**Comment by lavv17** [comment] 2017-09-25 10:17
4.8.1 has some problems, 4.8.2 will be released shortly.

**Closed by lavv17** 2017-09-25 10:17 UTC

**Comment by Jonathon55** [comment] 2020-08-28 14:05
> when trying to connect to invalid ftp port, after the maxretries are consumed an exception occurs:
> 
> Fatal error: max-retries exceeded
> assertion "ptr(x.heap_index)==&x" failed: file "xheap.h", line 127, function: void xheap::remove(xheap::node&) [with T = Timer]
> 1 [main] lftp 20404 cygwin_exception::open_stackdumpfile: Dumping stack trace to lftp.exe.stackdump]
> 
> compiled with cygwin on Windows 10

How did you fix this?  Also got this error on windows 10. Have been trying to connect to sftp server, no luck
