### ISSUE TITLE
mirror fails to delete directories

### ISSUE THREAD

**Issue by rascrasc** [lavv17/lftp#152] opened 2015-05-28 15:13 UTC
Hi,

Trying to sync a directory tree from local filesystem (Unix) to a remote server (Windows), using FTP.
The mirror command is not able to remove a directory(tree) from the remote server, when these directory (Tree) is not in the local filesystem anymore (e.g. directory tree was deleted from local filesystem).

mirror  -vvv    -c -e -L --no-empty-dirs  -x \'$ignoremask\'  --reverse \'$localdir\' \'$remotedir\' 

lftp reports the message (remote server is a windows server):

>> Removing old directory `__TEST 123'
>> rmdir: Access failed: 550 __TEST 123: The directory is not empty. 

When mirroring a server, also directories should be mirrored (means: no directory on source, also no directory on target).

lftp is a great, powerful tool! But this bug makes it hard to use for syncing servers...

**Comment by lavv17** [comment] 2015-06-10 11:52
mirror of lftp tries to remove the directory recursively. Probably it could not remove some files from it. One of possible reasons is a hidden file inside the directory. Please check which files are left there. Also turn on debug in lftp to see what happens in more detail.

**Comment by rascrasc** [comment] 2015-06-17 21:39
Test:

Directory to sync: (local, Linux) /revdata/public    --> (remote ftp, win2012 Srv)  /rd-test

local directory content (Unix):
/revdata/public
/revdata/public/dir1
/revdata/public/dir1/file1234.pdf
/revdata/public/dir1/dir1-1
/revdata/public/dir1/dir1-1/file5555.pdf
/revdata/public/dir1/dir1-2
/revdata/public/dir1/dir1-2/file3333.pdf
/revdata/public/dir2
/revdata/public/dir2/filebbbb.pdf
/revdata/public/dir3
/revdata/public/dir3/aaaaaaaaa.pdf



Remote directory content (Windows 2012 Srv) (FTP)
/rd-test
/rd-test/dir1
/rd-test/dir1/file1234.pdf
/rd-test/dir1/dir1-1
/rd-test/dir1/dir1-1/file5555.pdf
/rd-test/dir1/dir1-2
/rd-test/dir1/dir1-2/file3333.pdf
/rd-test/dir2
/rd-test/dir2/filebbbb.pdf
/rd-test/dir3
/rd-test/dir3/aaaaaaaaa.pdf
/rd-test/to_be_deleted_test
/rd-test/to_be_deleted_test/test123.pdf


Files were mirrored from local to remote using lftp
Then directory "to_be_deleted_test" has been removed on local directory
Next mirror run should remove this dir/files from target, but doesn't work.

On remote site: access rights are ok, no hidden files.


>>>>
mirror -c -e -L --depth-first -x .*(what|so|ever).* --reverse /revdata/public/. /rd-test
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir1
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir1/dir1-1
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test/dir1/dir1-1
<--- 250 CWD command successful.
---> PASV
<--- 227 Entering Passive Mode (ipXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXX) port 50918
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM file5555.pdf
<--- 213 20150617160720
---> CWD /
<--- 250 CWD command successful.
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir1
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir1/dir1-2
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test/dir1/dir1-2
<--- 250 CWD command successful.
---> TYPE A
<--- 200 Type set to A.
---> PASV
<--- 227 Entering Passive Mode (XXXXXXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXXXX) port 50919
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM file3333.pdf
<--- 213 20150617160720
---> CWD /
<--- 250 CWD command successful.
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir1
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test/dir1
<--- 250 CWD command successful.
---> TYPE A
<--- 200 Type set to A.
---> PASV
<--- 227 Entering Passive Mode (XXXXXXXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXXXX) port 50920
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM dir1-1
<--- 550 The specified path is invalid.
---> MDTM dir1-2
<--- 550 The specified path is invalid.
---> MDTM file1234.pdf
<--- 213 20150617160720
---> CWD /
<--- 250 CWD command successful.
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir2
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test/dir2
<--- 250 CWD command successful.
---> TYPE A
<--- 200 Type set to A.
---> PASV
<--- 227 Entering Passive Mode (XXXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXXXX) port 50921
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM filebbbb.pdf
<--- 213 20150617160720
---> CWD /
<--- 250 CWD command successful.
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> MKD /rd-test/dir3
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test/dir3
<--- 250 CWD command successful.
---> TYPE A
<--- 200 Type set to A.
---> PASV
<--- 227 Entering Passive Mode (XXXXXXXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXXXXXXX) port 50922
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM aaaaaaaaa.pdf
<--- 213 20150617160720
---> CWD /
<--- 250 CWD command successful.
---> MKD /rd-test
<--- 550 Cannot create a file when that file already exists.
---> CWD /rd-test
<--- 250 CWD command successful.
---> TYPE A
<--- 200 Type set to A.
---> PASV
<--- 227 Entering Passive Mode (XXXXXXXXXXXXXXXXXXX).
---- Connecting data socket to (XXXXXXXXXXXXXXX) port 50923
---- Data connection established
---> LIST
<--- 125 Data connection already open; Transfer starting.
<--- 226 Transfer complete.
---- Got EOF on data connection
---- Closing data socket
---> TYPE I
<--- 200 Type set to I.
---> MDTM dir1
<--- 550 The specified path is invalid.
---> MDTM dir2
<--- 550 The specified path is invalid.
---> MDTM dir3
<--- 550 The specified path is invalid.
---> MDTM to_be_deleted_test
<--- 550 The specified path is invalid.
---> RMD to_be_deleted_test
<--- 550 The directory is not empty.
rmdir: Access failed: 550 The directory is not empty.  (to_be_deleted_test)

<<<<

I hope this helps....

**Comment by lavv17** [comment] 2015-06-18 08:43
The problem was caused by "--depth-first" option. If you omit it, lftp should successfully remove the directory. BTW, the bug was fixed by the just released 4.6.3a, please test.

**Closed by lavv17** 2015-06-18 08:43 UTC

**Comment by bagong** [comment] 2020-06-02 22:37
I get the same problem with 4.8.4 on Ubuntu server. The remote system is a Fritz-box with a linux I don't know. The directory not removed is hidden (".certificates"). Can lftp not recurse through dot-files?

**Comment by bagong** [comment] 2020-06-02 22:45
Yes, after I renamed it to "certificates" it got removed. There are possibilities of even more hidden systemfiles like MacSh*t a la "._.xyz" (Finder tags) or so... It's a shame if those block a directory delete...
